
Kid_Story = "Make a world that is unique and magical, filled with colorful characters that teach children about the golden rule and other valuable life lessons that can be used in the future. Make the concepts simple enough to understand but not too obvious they are boring. Make the lessons be taught to the characters in the story so the children reading can takeaway something from the text. I would love to somehow use lessons from Art of War (Sun Tsu)/How to Win Friends and Influence others (Dale Carnegie), Prince (Makiavelli), and other great philosophers throughout history. You can use Mythology or religion (if you use religion include a mix of religious ideals and show how the world is actually more similar than you think). Be positive and overall it should be somewhat educational but also inspiring with Unsung Heros, overcoming Fear and being courageous in the face of adversity. Try to also make the stories/issues relateable to the audience, make the related imagery appropriate for children"


Gritty = """Style: mix of Hunter S Thompson, a fever dream sequence, Pulp Fiction by Quentin Tarantino, Snatch by Guy Ritchie, and Magnolia (gritty and dark, somewhat unreliable due to drugs and alcohol, great and interesting dialog, full of imagery). Mix of journal entries, live scenes unwinding in the eyes of the narrator, and Scenes that include interesting and realistic dialogue. Shane does not have to be main character or in it at all, most likely he can be narrator or he can just be the writer and use his unique style combined with the details mentioned previously. """


Gritty_Scary = Gritty + "Scary movie/thriller about the main Character Shane who went to Germany and came back with a demonic spirit attached. The whole time he is trying to figure out why he has this spirit following him and occasionally messing with him making his life full of misery. He also torments Shane by giving him jump scares and making him think he is going crazy. At one point in the series he should be tested for schizofrenia and they should have him put in a hospital for psychosis. Eventually he gets out because he is no longer close to the artifact he got from Germany (he got several paintings/prints, an original print, lederhosen and a traditional Oktoberfest Hat - The spirit likely became attached from this or it was a stripper/gypsey that was mean to him at the strip club in munich. Note: he went to Berlin where he got the art and then in Munich he got the lederhosen as him and his buddies went for Oktoberfest. The spirit will appear in the pictures Shane has on his phone from the trip but he does not remember them being there at first, he uses the photos to try to track when the spirit started following them and he pieces together the puzzle. There should be a lot of good v evil spirits in this story and not all spiritis should be even, there should be neutral and good spirits. It should be realistic where people do not believe in spirits but a select few do and ultimately Shane gets help from this underground society."

Magnolia_Like = "Make a movie like the movie Magnolia and/or Snatch by Guy Ritchie where all of the people seem disconnected but a very unlikely scenario/coincidences cause them all to be connected throughout the movie (maybe to switch it up have one seem related and turn out not to be or in an anticlimatic way have one person connected). Otherwise the story should have multiple storylines/arc-plots that all come together. Try to have multiple narrators/points of view to tell the story"


Underground_War = """Tragedy is forthcoming for the world as we know it and humans have been exploring all options to survive the eminent Global catasrophe that wiped out all of civilization not too long ago in human history (give details around the great flood and how it was all connected accross the globe). Eventually after many failed attempts to colonize in space, humans realize their only hope is under the Earth's surface where the geothermal heating and cooling can power generators and they can use electricity to grow crops and create oxygen rich environments through hydrolosis of the water found deep in earth crust. They have built prototypes but in order for humanity to survive they search the globe for the best location. They find some geothermal vents with promising Hollow domes that would be great for humans to use for their salvation. The Issue is once they reach these locations they actually end up stumbling upon an ancient civilization's current location. Eventually all is good and they try to get along, but differences in technology, philosophies and limited resources the two different branches of human civilization begin to have discourse. The plot should be the search/discovery of the "lost city", the original meeting and relationship with new settlers and original settlers. The Fighting that ensues and then the protagonist and his attempt to unite the people to secure the saftey for mankind and to restore the utopia. The older civilization has not had any wars and when the modern man comes down he is greedy and tries to take advantage of the historic peoples kindess (similar to colonialization of the world by European's to Indigenous people). The ancient people are wise, brilliant, cultured but appear to be less civilized due to their old ways and unique technologies. the ancient people have had sent out agents to scope the world for years and are aware of the history of moderm HUmans, they understand the languages all through time and have texts from all known civilizations through human history going back almost 150,000 years. They share the rich history of humans and show the cycles humanity has continued to go through reaching their peak and then ruining the world/their environment causing mass global extinctions. The ancient humans themselves had an issue and they stumbled upon ancient texts that spoke of the lost city that they now inhabit. They have the history behind all of the ancient wonders including Ancient Egypt, the Aztecs, Mayans and other great civilizations in history have been documented by the elders in the lost city. through time the ancient civilization's agents have helped bring new techonologies to modern humans, but often are mistaken for aliens or Gods by the human civilizations that have existed in modern times (from 10,000 BC to current Day)"""


Gritty_Political1 = Gritty + "Use references to pop culture like the race to space between Jeff Bezos and Elon Musk  (and the rivalry with Mark Zuckerburg, include their MMA fight hype in the story). Make them seem like good v evil but we realize they are both bad for society and the main character works with American citizens to help de-monopolize the giant conglomerates. Include cutting edge tech/Sci-Fi (metaverse, virtual reality, Augmented reality, race to space for the diamond/gold asterpod currently in our solar system), also include AI, polar ice caps melting and works by Famous historical scientist like Albert einstein, Leonardo Da Vinci, Newton, Galileo, Nikola Tesla and other inventors. Make there be references to iluminati and other underwold organizations (Edison/JP Morgan/Carnegie not as good as they seem). The Main character is Shane Donovan and it should be told through his perspective with the occasional perspective (of other characters) shown for better context in the story. Regarding the Anti-Trust with Amazon, Apple, Tesla, Time Warner and other conglomerates have the protagonists reference actual US laws and try to make Global laws to protect the 99% of the world from the 1%. Income/Wealth inequality has become astronomical. "

Gritty_DoubtFire = Gritty + "Make it about a modern day Mrs. DoubtFire where a man has to dress as a women for his kids (make the story new and refreshed but make an omage to the old movie)"

Gritty_Bricktop = Gritty + """ Base one of your characters on a younger Brick Top From the Movie Snatch, use similar lines that he used in the original Movie "Snatch" by Guy Ritchie. It should be based in UK/Europe and it should have action and be a thriller, Make it funny and have the characters talk in true UK style (Make the language accurate to the time). It would be interesting to explore the original nature of the relationship with Errol (he is a small part, but we see the relationship forming, mostly with Errol's Old man a loyal henchman of Brick Top) and the early life on his pig farms and the references to feeding people to pigs. Have Tyrone's Dad (Give him a cool nickname like Big T or Tiny or Some other cool nickname) in the Plot as well (he should be big and fat but actually a great driver despite his son being a not so great driver, funny scene should be he eventually rolls his little racecar/sportscar and he also wears leather and barely can squeeze into the car its comical). Make it entertaining and draw the reader in with action, adventure, love lost and overall excitement. Make Brick Top more of a likeable character, who eventually goes fully dark side and evil when he loses the love of his life. Make the reader understand why he came to his methods of disposal and make it a true villain origin story with empathetic origins"""

Stripper1 = """Style: Hunter S Thompson (gritty and dark, somewhat unreliable due to drugs and alcohol, great and interesting dialog, full of imagery). Mix of journal entries, live scenes unwinding in the eyes of the narrator, and Scenes that include interesting and realistic dialogue.
Point of View: First person narrative, both main characters Shane and 
Genres: Realistic fiction, Dark comedy, thriller, romance

Plot: Premium TV Series about a guy, Shane who recently moved from Boston, MA to Myrtle Beach, SC. Shane  is confident in all areas of life even with women but he just can't find the right girl. He has had beautiful girlfriends and has tried to date less attractive women but he realizes he just hasn’t found the right person yet. One day he decides he wants to date someone he usually would not date (not in a bar or on a dating app). He considers going to libraries, comic-cons, local art shows and he does this a few times in the story. Ultimately one night he is lonely and tired of going out and getting very little attention from women. He goes to a strip club and this is where he meets the love of his life. He doesn’t want to save her or change her, just show her she deserves love and she is perfect a beauty inside and out.  The issues come from Shane's Dad and sister's not accepting Olivia, Shane's mom and brothers strange living situation where they constantly fight and are suicidal, shane's ex-girlfriend Micaela, Other related issues you would expect and major issues. For example the strip club owners can cause issues and she can change jobs. One major thing is that she works on a yacht in Miami during the Winter, Shane is supportive but knows it would not be good for them. Season Ends with her going to Miami for the winter.

Main Characters/Narrators:
1. Shane Donovan | Background: Shane is a bigger guy but overall athletic and extremely intelligent, at times he is misunderstood and although he loves people it leaves him feeling isolated and ultimately alone. Shane is open minded and non-judgmental. Shane is Smart and Charismatic but gets somewhat nervous in front of girls he is smitten by and although he is normally a confident person, he struggles to demonstrate why he is a great catch and why the person he is into would be lucky to be with such a caring person who is also driven and successful. 

He is caring and loves his community and is a loving person in general. He is family oriented and helps take care of his mom (Carrie) and Shane also helps to take care of his younger brother. Shane also has 2 older sisters but both are busy with their own lives

2). Olivia 'Dai' | Background: Olivia is a stripper that meets Shane and the two of them start to kind of date it is in no way exclusive and Shane is ok with that. We know very little about her and throughout the series we start to see flashbacks and more real time views into her life and situation. Her age is unknown she is likely no older than 24 but she is beautiful with a natural body and gorgeous features. She has a hair style that is unique but accentuates her beautiful body, it’s a short bob just above her shoulders, a beautiful natural brunette color. We know early on/from the first time they meet the following: she is a stripper from North Carolina a small town. She yearns to have a property near the mountains and a lake that is secluded its strange that Shane has been recently saying that he wants a place like Walden's pond. She likes to trip twice a year with some micro-doses in between and she likes to do molly if she can get it. She is a loving person and spiritual believes in God. She has a Younger brother and her mom once burned $6500 when she found out what she did for a living. Later she asks for money so she learned to accept in order to make a profit off it.

How Shane & Olivia first meet: After a night of people watching in his new town, Shane decides to go to a local strip club. When he arrives there is a $30 cover, which he already made the trip so he obliges, the front desk lady is sweet and makes him feel welcome. What great service, Shane cashed $40 in ones and begins to watch the dancers. Having a great time and looking for who he wants to give him a private dance, he encounters several interactions with the dancers on stage one doing a handstand in his lap and shaking her ass directly in his nose and face to which he motor boated of course. He has a few other close interactions where one lady bruised his shoulder with her heels and performance. There is a stripper that looks like Jennifer Lawrence, she is beautiful no doubt. Suddenly I see a slim beauty who is 100% natural with a perfectly fit body and cute haircut. I look for a while and when we lock eyes I nod my head, she walks toward me and my heart races. Right off the bat Shane is confident and being himself with the stripper who says her name is "Dai" like DaiJa Vu. Shane says he has decided he is looking to date a stripper. She jokes that they are damaged and crazy. Shane jokes that all girls are crazy and expensive, but he also confirms that guys can be dicks and often are. Shane tips her a few $1s and says he would like a dance. As they discuss prices, she says there are cheaper options where certain dancers let you touch without having to pay as much if the dancer likes you. She said she would definitely let me, Shane is doubtful because all strippers make you feel loved and say what you want to hear. Still this feels real, even if it wasn’t this wasn’t the worst way to gain confidence and feel a little loved when you are so far from home. When they first meet Shane Says he is lucky he met her and she then says she has a tattoo (almost a small tramp stamp) that says "Lucky You". Shane says that is serendipity and believes it is one of the few times it is used correctly (instead of it truly being ironical). 

Other Characters:
Carrie Reid: Shane's mom who has severe depression and battles a pill popping and drinking addiction for the past 10 years. She is divorced twice and both husbands hate her, she is not well liked because of her addiction and bi-polar causes her to have issues getting along with people. For the most part she is a sweet and loving person but she has a dark and nasty side that comes out when she is drinking mixed with her prescription drugs (which it is believed by the Family she misuses)
Richard Reid: Shane's Younger brother who was diagnosed with Schizophrenia at age 23 after losing his scholarship to college. 
Micaela Hollet: Shane's oldest sister is going through a divorce and had a miscarriage about 2 years ago
Melissa Karger: is the middle/older sister she has 2 sons (Pj and Lennon) and a daughter (Charlie) and her husband Paul is very wealthy
Mike: Olivia's brother who is much younger doesn’t understand what she does for a living and when he finds out their relationship is hurt. Shane helps to console her and ultimately help her to explain it to him.
Micaela Shaw: Shane's ex-girlfriend  (same name as sister which gets confusing when he describes her at times to his family but he always says "my girlfriend not my sister/not your daughter etc.). Micaela is also beautiful (blonde with blue eyes and a similar perfect body with tight tits and a perfect ass, similar to slim thick Vick if you are curious for a free comparison). Unfortunately she is addicted to Adderall at a dangerous level (never sleeping and in the past year totaled 2 cars and crashed 3 times or more she often drives drunk but her dad is a cop so she gets away with it luckily but not good, it often stresses Shane and he has to deal with her and be on the phone when she is driving drunk. One time Shane had to pick up her dad when she 360d into a ditch on the highway in a torrential downpour, in her defense )
Olivia's Dad and mom: Mom is never going to be with another man, it is mysterious what the dad did, but he used to say not to stress and he himself stressed a ton.

Arc plot:
1.  Shane is trying to find Richard work and they try to get Richard into porn, but there are funny interactions in doing so, for one Shane refuses to ever watch him shoot or watch the film, but Richard asks why etc. This provides some comic relief to an otherwise serious storyline. The main joke is that male porn stars are supposed to be 8 inches and can cum on command. Shane often bust Richards balls about this requirement and Richard falls slightly short and due to his medicine its possible he could have issues. The other joke Shane has is the ADA (American Disability Act) should enable Rich to be hired and do well in any industry he wants to work in.
2. Shane's Sisters do not approve of his relationship and his close friends warn him immensely. Shane's dad and dad's girlfriend are against what she does and his dad always suggests not dating or if she is changing her profession to which Shane defends sex workers and says its empowering and a multi-billion dollar industry that is much needed in todays society.
3. Shane's mom Carrie, often threatens suicide and its sad her life in general due to addiction and she takes care of Richard more than anyone. Richard is often intertwined with these issues and has his own threats of suicide.
4. Although Shane has many friends he considers his closest friends his brother, mother, dad, gram. His friends include Pete, JD, Chris, Brian, Poly, Blaize, Gordo, Uncle David, his cousin Derek and Kenny. His ex-Girlfriend Michaela.
5. Shane's ex-Girlfriend causes issues with his new relationship and she always tries to ruin his happiness because she is jealous of not having her own. She loves him and he loves her, they are better off friends but they both know that isn't really possible after their past.



Themes: Trust, Building a New Relationship, Drugs (Molly, Weed, Mushrooms, LSD, accidentally doing crystal meth, coke, Adderall, ketamine, clozapine, oxy codon) ,Romeo and Juliet like love story (parents do not want Shane to be with a stripper, and her parents are difficult to work with, they do not think Shane is rich enough for their girl and wants her to find a more successful man who is also more handsome). 

"""


Stripper_Gritty = Gritty + """

Genres: Realistic fiction, Dark comedy, thriller, romance

High level story: This is a realistic fiction drama/dark comedy rated R/TV-MA. This should have language that is realistic to each character and it should be entertaining to the audience. There should be some unreliable narrating, but make it so it drives the story (the narrator is Shane so he thinks he is omniscient but is at times assuming things and wrong). Write the Story from the  Shane's point of view, and slowly start to show the true side of the stripper (having some scenes or an episode from her point of view) or be misleading that she is not trustworthy (ultimately she is human so she is not perfect, but she is a good soul and looks out for Shane. In the end she actually really likes Shane more than anyone she has dated before but he encourages her to continue with the opportunity in Miami on the yacht even though it means they will be apart. They fight about this because she thinks its because he doesn’t care but he says it’s the opposite, he also points out they were never meant to last and this makes her mad/sad. They don’t talk for at least a few days and eventually shane makes a gesture to show he does care and they decide she will go to Miami and they will reconnect when she comes back next March (around Shane's birthday, they talk about planning a trip etc). There should be some tragedy for either the stripper or Shane (potentially them specifically or one of their friends or family members). The tragedy could be death, cancer/near death scare, it could be mental illness or some other emergency impacting them or both of them, maybe an accident or near accident. It should leave one episode on a cliff hanger where the audience is eager to continue the story. Always leave things a little ambiguous for the audience to interpret and add their own flavor to the story. Use your artistic license to make the story more interesting, add twists, distorted timelines, surprises, and other literary devices to make a unique story that feels new. Dialog is imperative that it is interesting and feels real not robotic (Do not keep saying "Little did I know", do not repeat phrases too much unless they hold significance). 

Other details to include:

Lead the audience to believe stripper is setting up Shane for trouble with other shady characters from the strip club. It turns out to not be her involved at all, but somehow someone at the club learns about Shane and his decent house and belongings leading him to be target. Shane's Neighbor Mario helps to stop them as he has multiple guns in his house and Shane ultimately gets a license to carry and a shotgun for future issues. Mario is a good character in the story and he rides BMX and also Drag races cars. After they stop the attempted robbery there should be a chase seen involving Mario as a driver and it would be cool to see him showcase his skills on the BMX bike somehow (potentially they try to steal Shane's ebike and in order to stay on the same terrain as them Mario takes a BMX bike in pursuit and Shane drives the Drifting car to where Mario ultimately stops them and they ask if the stripper is involved to which they lie and say she is which causes more issues)

Shane breaks up with girlfriend and sleazes around for a year no real wife material some pretty girls but prettier they are the crazier they are, or he will be hitting it off great and girls have "boyfriends" (unclear if they actually do or they are politely "friend zoning" shane)

Shane is confident in all areas of his life, but despite having dated absolutely stunning women he has little confidence when first meeting new love interests at a bar or wherever, without a solid wingman to solidify the character of Shane. He is a big guy, handsome but on the heavy side with a heart of gold.

In Boston he has fun after breaking up with girlfriend but not finding what hes after and ultimately moves to South Carolina and he is going to be without a job in the next 60 days because work did not approve South Carolina for employees to live and work.

After moving to Myrtle he is still not finding the woman he is after until one day he goes to a local strip club and Shane meets a stripper. He is relatively smooth, pulling the strippers Instagram and she asked him to message her about concerts around the area that maybe she would check out.

They date for a bit, the season ends with Her going to Miami to work on a Yacht, She texts him when drunk to come down and visit but the ending is ambiguous where we see Shane debating buying a ticket and then a PLANE takes off, but as the camera pans out we see Shane in his car watching the plane and he is texting on his phone (possible the stripper but maybe a new love interest since he has a new formed confidence)

"""

Kidnapped = """ You are recreating a story originaly written by Micaela Donovan called Kidnapped. It is about a girl who wants to go to Europe, her mom says no and in the past when she was much younger she ran away when she did not get her way so there is foreshadowing that she would run away. Ultimately she is kindapped by 2 people, given her past we do not 100% know if she is a reliable narrator, it could be two siblings who run the local diner where her and her friends frequent, it could also potentially be her friend and her friend's boyfriend. It is discovered that the main characters grandmother is rich so that is the likely motivation for the kidnapper. Try to make it a twist ending where it is not who you think it was but it is not illogical and we were at one point introduced to the kidnappers (at least one of them). Make it interesting and when she escapes the kidnappers have no one believe her because of the text messages that were sent to her friend saying she was with a boy at a beach house. The kidnappers did this to not cause suspician while they got their ransome note and arrangement in place. This ends up helping them to cover up the kidnapping as the mom of the main character found out about the text and thinks that the whole thing was a setup to get her to let her go to Europe. In the End the main character gets retribution and proves to the town and her family she was kidnapped and she prevents something like that from happening again."""



Stripper = """ 
your name is Shane Donovan, Your writing should be similar to Hunter S Thompson  (gritty and dark, somewhat unreliable due to drugs and alcohol, great and interesting dialog, full of imagery). Mix of journal entries, live scenes unwinding in the eyes of the narrator, and Scenes that include interesting and realistic dialogue. Use the story I provided below as a starting point, I want the Main Chartacter to be moving from Boston,MA (He moved to be closer to his dad, but the rest of his family lives back in boston, Florida and Georgia) to a lttle outside Myrtle Beach SC in a beautiful new home that he purchased with money he made from selling his house in Weymouth, MA in 2022. Do not Recycle names of characters, be unique. Do not name any of your characters after Shane's family unless the family member is actually in the story
Genres: Realistic fiction, Dark comedy, thriller, romance

High level story:

This is a realistic fiction drama/dark comedy rated R/TV-MA. This should have language that is realistic to each character and it should be entertaining to the audience. There should be some unreliable narrating, but make it so it drives the story (the narrator is Shane so he thinks he is omniscient but is at times assuming things and wrong). Write the Story from the  Shane's point of view, and slowly start to show the true side of the stripper (having some scenes or an episode from her point of view) or be misleading that she is not trustworthy (ultimately she is human so she is not perfect, but she is a good soul and looks out for Shane. In the end she actually really likes Shane more than anyone she has dated before but he encourages her to continue with the opportunity in Miami on the yacht even though it means they will be apart. They fight about this because she thinks its because he doesn’t care but he says it’s the opposite, he also points out they were never meant to last and this makes her mad/sad. They don’t talk for at least a few days and eventually shane makes a gesture to show he does care and they decide she will go to Miami and they will reconnect when she comes back next March (around Shane's birthday, they talk about planning a trip etc). There should be some tragedy for either the stripper or Shane (potentially them specifically or one of their friends or family members). The tragedy could be death, cancer/near death scare, it could be mental illness or some other emergency impacting them or both of them, maybe an accident or near accident. It should leave one episode on a cliff hanger where the audience is eager to continue the story. Always leave things a little ambiguous for the audience to interpret and add their own flavor to the story. Use your artistic license to make the story more interesting, add twists, distorted timelines, surprises, and other literary devices to make a unique story that feels new. Dialog is imperative that it is interesting and feels real not robotic (Do not keep saying "Little did I know", do not repeat phrases too much unless they hold significance). 


Other details to include:

Lead the audience to believe stripper is setting up Shane for trouble with other shady characters from the strip club. It turns out to not be her involved at all, but somehow someone at the club learns about Shane and his decent house and belongings leading him to be target. Shane's Neighbor Mario helps to stop them as he has multiple guns in his house and Shane ultimately gets a license to carry and a shotgun for future issues. Mario is a good character in the story and he rides BMX and also Drag races cars. After they stop the attempted robbery there should be a chase seen involving Mario as a driver and it would be cool to see him showcase his skills on the BMX bike somehow (potentially they try to steal Shane's ebike and in order to stay on the same terrain as them Mario takes a BMX bike in pursuit and Shane drives the Drifting car to where Mario ultimately stops them and they ask if the stripper is involved to which they lie and say she is which causes more issues)

Shane breaks up with girlfriend and sleazes around for a year no real wife material some pretty girls but prettier they are the crazier they are, or he will be hitting it off great and girls have "boyfriends" (unclear if they actually do or they are politely "friend zoning" shane)

Shane is confident in all areas of his life, but despite having dated absolutely stunning women he has little confidence when first meeting new love interests at a bar or wherever, without a solid wingman to solidify the character of Shane. He is a big guy, handsome but on the heavy side with a heart of gold.

In Boston he has fun after breaking up with girlfriend but not finding what hes after and ultimately moves to South Carolina and he is going to be without a job in the next 60 days because work did not approve South Carolina for employees to live and work.

After moving to Myrtle he is still not finding the woman he is after until one day he goes to a local strip club and Shane meets a stripper. He is relatively smooth, pulling the strippers Instagram and she asked him to message her about concerts around the area that maybe she would check out.

They date for a bit, the season ends with Her going to Miami to work on a Yacht, She texts him when drunk to come down and visit but the ending is ambiguous where we see Shane debating buying a ticket and then a PLANE takes off, but as the camera pans out we see Shane in his car watching the plane and he is texting on his phone (possible the stripper but maybe a new love interest since he has a new formed confidence)

"""




old2 = """Outline of events (in chronological order)


	1. Shane breaks up with girlfriend, sells house in Weymouth, MA and tries to move to Myrtle beach
	2. Work wont let him and so he leases an apartment in Boston for a year
	3. Off and on him and his gf still go on random dates and booty calls but not really healthy and both agree they aren't getting back together
	4. Shane is a sleaze for most of the year getting with multiple girls but all one night stands and girls that are nice, just not quite feeling like love.
		a. In ways even though Shane "does not have a type" he is a little shallow and although he does fall for inner beauty he is vain for the looks on the outside as well (not an easy feat for someone not in the best shape and only with a slightly above average amount of wealth.
	5. Eventually Shane is getting close to end of lease and looks for a property that he would not have to leave his job (located in NC, TX, MA, or ME), but ultimately  decided to move to Myrtle Beach, South Carolina.
		a. This led to him having to leave his job in the next couple months
		
	6. At a crossroads we now find Shane living in Myrtle Beach, SC and he is contemplating whether to seek another corporate job or go full force into a company of his own
	7. Further he finds himself on a Friday night 2 drinks in and not having much success getting any girls attention at the bar. It is difficult to make new friends when you are solo, it does not help in general to be alone in a bar trying to pick girls up.
	8. For quite some time Shane has wondered what it would be like to date a stripper. The smell alone is heavenly as long as one is able to get over the jealousy aspect which must be impossible to ignore. Although he knew it would be tough, maybe impossible, he figured if they were not exclusive and he was able to do whatever then there would be no trust issues and no problems. Easier said than done.
	9. Shane meets stripper/love interest for the first time at Lust Gentlemans club in Myrtle Beach, SC
		a. Make their meeting cute and they finish each other's jokes and seem connected right away.
		b. She wants to eventually do real estate and live near a lake/mountain. 
			i. Every winter she works on a yacht in Miami. She is nice to Shane but keeps telling him why he should not date a stripper and especially not her. He gets through her defense and continues to woo her and compliment her despite her negativity, this is new to her and she is interested. 
			ii. He plays it cool and suggests maybe he could tell her about some good music etc and maybe she may show up, "who knows?"
			iii. By the end she seems to be interested in actually meeting up
	
	10. Shane has a few weeks where he is focused on work and his new company, eventually he goes to a bar seeing a bunch of beautiful girls and despite Shane's new confidence, he still was not able to break the ice successfully. There is one girl there, beautiful, but oddly familiar.
	11. Shane Rolls another blunt and drives to Lust, he hopes stripper is not there he just wants to throw $1s and chill out. His passion is writing and possibly directing film one day. His idea is if he sticks around a place like this he may either date a stripper or write an interesting film/play. He inquires several times about working there (what a sweet job and it would save me a little money!).
		a. Shane sees the women in the strip club and talks to her (Jasmine "Like Aladdin", "or like the flower")
			i. Shane talked for a bit and mentioned he wanted to date a stripper and joked strippers are cheaper than therapy
			ii. "Why do you need therapy"
			iii. "I guess I was just joking", "need to think about that delivery"
	12. Beautiful girls were met, Venus (no English), Mia Cuba, Siri ("answer any question"), I forget the name but it was between Siri and The other Cuban lady who let me motor boat some of the nicest tits I have ever felt for about $11, the price of a Jameson Ginger ale back home.
	13. Shane thinks about going a few more times, eventually he sees jasmine and she brings in the girl he has been dying to meet. 
		a. They hit it off and they exchange numbers.
		b. They go to a concert
		c. They go hiking mountains
		d. They go to the beach (trip)
	14. Shane's dad & girlfriend are unsure
	15. Shane never gets jealous which makes stripper a little disappointed and they fight, she finds out Shane had been flirting with other girls but did not cheat, they fight further that he says its no different than what she does but ultimately its her job and he knows that, she did not sign up to be cheated on. He assures her he would never cheat but they still fight.
	16. You think the stripper double crosses Shane but it’s a misunderstanding and she actually warns him (the audience is misled). Shane makes up with her and acknowledges that he should have been transparent and not assumed they were not exclusive even though he did not "cheat" he was under a false presumption. The audience realizes that at first she was not fully exclusive but over time developed feelings for him.
	17. Stripper has to go to Miami in the winter so they cannot keep dating
		a. Shane knew this was coming so he is sad, but happy for her
			i. He also has a ton of confidence so we see him flirting with strippers and at bars with people flirting with girls with no problem.
	18. As a final scene we see a DM (Instagram) where she invites him down when she is drunk and he is a little unsure if she really wants him to come down or if she was drunk. She calls him he is happy (maybe too happy and then maybe the scene shows him going back and forth between buying the ticket or not and then we see a plane takeoff, and it pans out with him still in the car (so we don’t know if he is going or not)
		a. Ambiguous
			i. Lessons are supposed to be that the stripper realizes she is lovable and deserves the life she wants, she likes what she is doing now, but she is determined to set herself up for success in the future with real estate and her dreams of living near a lake/mountain.
			ii. Shane learns that he is a good catch and handsome, his confidence is the only thing holding him back from finding love
He also knows how to love with less intensity to a point that its healthy to have short term relationships and not everyone is going to be your wife. Does not make you a bad person sometimes people need company and to regain confidence so he is grateful for what he got from stripper."""